# provision_staging.yml
---
- name: Create ec2 instance
  hosts: all 
  vars_files:
  - vars.yml
  vars:
    instance_type: 'm3.large'
  tasks:

  - name: Create instance 
    ec2:
      key_name: chouse
      instance_type: "{{ instance_type }}" 
      image: ami-46c1b650
      wait: yes
      wait_timeout: 360
      group: ansible-container 
      instance_tags:
        awx-demo: true
#        awx-user: "{{ instance_tag }}"
#        awx-dev: true
      count_tag:
        awx-demo: true 
#        awx-user: "{{ instance_tag }}"
      exact_count: 2
      vpc_subnet_id: subnet-65a3522e
      assign_public_ip: yes  
      region: us-east-1
      termination_protection: yes
    register: ec2
  
  - name: Add new instance to host group
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: myhosts 
      ansible_user: centos
    with_items: "{{ ec2.instances }}"
    when: ec2 is defined

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 60
      timeout: 320
      state: started
    with_items: "{{ ec2.instances }}"
    when: ec2 is defined

- name: Configure new instance
  hosts: myhosts 
  become: yes
  roles:
  - role: docker

